import Head from 'next/head'
import Hero from '../components/Hero';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="Hi, I'm Eugene. A Software Engineer." message="I solve problems through code, design, and critical thinking."/>
      <Slider slides={SliderData} />
    </>
  )
}
